package store

import (
	"context"
	"database/sql"
)

const initSchemaUp = `
CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mission_priority INT NOT NULL,
    leader_position  INT NOT NULL,
    speaker_position INT NOT NULL,
    
    skips_count INT NOT NULL DEFAULT 0,
    wins        INT NOT NULL DEFAULT 0,
    fails       INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    name       TEXT NOT NULL,
    max_fails  INT  NOT NULL,
    squad_size INT NOT NULL,
    priority   INT  NOT NULL
);

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    name     TEXT NOT NULL,
    model    TEXT NOT NULL,
    role          TEXT NOT NULL,
    voice         TEXT,
    mood TEXT,
    position INT NOT NULL
);

CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    model  TEXT NOT NULL,
    
    system_prompt TEXT NOT NULL,
    
    message_prompt TEXT NOT NULL,
    
    response TEXT NOT NULL DEFAULT '',
    
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
   
    status TEXT NOT NULL DEFAULT 'NOT_STARTED'
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'SPEECH',
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_missions_game_id ON missions(game_id);
CREATE INDEX IF NOT EXISTS idx_players_game_id  ON players(game_id);
CREATE INDEX IF NOT EXISTS idx_missions_priority ON missions(priority);
CREATE INDEX IF NOT EXISTS idx_prompts_game_id ON prompts(game_id);
CREATE INDEX IF NOT EXISTS idx_events_game_id ON events(game_id);
`

func RunInitMigration(
	ctx context.Context,
	db *sql.DB,
) error {

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if _, err := tx.ExecContext(ctx, initSchemaUp); err != nil {
		return err
	}

	return tx.Commit()
}
