package store

import (
	"context"
	"database/sql"
)

const initSchemaUp = `
CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mission_priority INT NOT NULL,
    leader_position  INT NOT NULL,
    speaker_position INT NOT NULL,
    phase            TEXT NOT NULL DEFAULT '',
    turns_order      INT[] NOT NULL DEFAULT '{}',
    
    skips_count INT NOT NULL DEFAULT 0,
    wins        INT NOT NULL DEFAULT 0,
    fails       INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    name          TEXT  NOT NULL,
    status        TEXT  NOT NULL DEFAULT '',
    max_fails     INT   NOT NULL,
    allowed_fails INT   NOT NULL DEFAULT 0,
    squad_size    INT   NOT NULL,
    priority      INT   NOT NULL,
    squad         INT[] NOT NULL DEFAULT '{}',
    progress      INT   NOT NULL DEFAULT 0,
    fails         INT   NOT NULL DEFAULT 0,
    successes     INT   NOT NULL DEFAULT 0,
    skips         INT   NOT NULL DEFAULT 0,
    leader        INT   NOT NULL DEFAULT 0,
    votes         JSON  NOT NULL DEFAULT '[]'::json
);

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    name TEXT NOT NULL,
    model TEXT NOT NULL,
    role TEXT NOT NULL,
    character_type TEXT NOT NULL,
    position INT NOT NULL,
    vote TEXT NOT NULL DEFAULT '',
    mission_action TEXT NOT NULL DEFAULT ''
);


CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,

    model  TEXT NOT NULL,
    
    system_prompt TEXT NOT NULL,
    
    message_prompt TEXT NOT NULL,
    
    response TEXT NOT NULL DEFAULT '',
    
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
   
    status TEXT NOT NULL DEFAULT 'NOT_STARTED'
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    player_id BIGINT REFERENCES players(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'SPEECH',
    content TEXT NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_missions_game_id ON missions(game_id);
CREATE INDEX IF NOT EXISTS idx_players_game_id  ON players(game_id);
CREATE INDEX IF NOT EXISTS idx_missions_priority ON missions(priority);
CREATE INDEX IF NOT EXISTS idx_prompts_game_id ON prompts(game_id);
CREATE INDEX IF NOT EXISTS idx_events_game_id ON events(game_id);

ALTER TABLE events ADD COLUMN IF NOT EXISTS player_id BIGINT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS hidden BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'events'
          AND column_name = 'source'
    ) THEN
        EXECUTE '
            UPDATE events e
            SET player_id = p.id
            FROM players p
            WHERE e.player_id IS NULL
              AND p.game_id = e.game_id
              AND p.name = e.source
        ';
    END IF;
END $$;

ALTER TABLE events DROP COLUMN IF EXISTS source;

CREATE INDEX IF NOT EXISTS idx_events_player_id ON events(player_id);

ALTER TABLE missions ADD COLUMN IF NOT EXISTS squad INT[] NOT NULL DEFAULT '{}';
ALTER TABLE missions ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 0;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS fails INT NOT NULL DEFAULT 0;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS successes INT NOT NULL DEFAULT 0;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS skips INT NOT NULL DEFAULT 0;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT '';
ALTER TABLE missions ADD COLUMN IF NOT EXISTS leader INT NOT NULL DEFAULT 0;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS allowed_fails INT NOT NULL DEFAULT 0;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS votes JSON NOT NULL DEFAULT '[]'::json;
ALTER TABLE players ADD COLUMN IF NOT EXISTS vote TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN IF NOT EXISTS mission_action TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN IF NOT EXISTS turns_order INT[] NOT NULL DEFAULT '{}';

ALTER TABLE games ADD COLUMN IF NOT EXISTS phase TEXT;
ALTER TABLE games ALTER COLUMN phase SET DEFAULT '';
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'games'
          AND column_name = 'game_state'
    ) THEN
        EXECUTE 'UPDATE games SET phase = COALESCE(phase, game_state, '''')';
    ELSE
        EXECUTE 'UPDATE games SET phase = COALESCE(phase, '''')';
    END IF;
END $$;
ALTER TABLE games ALTER COLUMN phase SET NOT NULL;
ALTER TABLE games DROP COLUMN IF EXISTS game_state;

UPDATE missions SET allowed_fails = max_fails WHERE allowed_fails = 0;
ALTER TABLE missions ALTER COLUMN allowed_fails SET NOT NULL;

UPDATE players SET vote = '' WHERE vote IS NULL;
UPDATE players SET mission_action = '' WHERE mission_action IS NULL;
ALTER TABLE players ALTER COLUMN vote SET DEFAULT '';
ALTER TABLE players ALTER COLUMN mission_action SET DEFAULT '';
ALTER TABLE players ALTER COLUMN vote SET NOT NULL;
ALTER TABLE players ALTER COLUMN mission_action SET NOT NULL;
`

func RunInitMigration(
	ctx context.Context,
	db *sql.DB,
) error {

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if _, err := tx.ExecContext(ctx, initSchemaUp); err != nil {
		return err
	}

	return tx.Commit()
}
