package constants

const ROLE_MERLIN = "Мерлин"
const ROLE_ARTHURS_LOYAL = "Слуга Артура"

const ROLE_ASSASSIN = "Ассасин"

const ROLE_MORDRED_MINION = "Миньон Мордреда"

const STATE_DISCUSSION = "DISCUSSION"
const STATE_VOTING = "VOTING"
const STATE_MISSION = "MISSION"
const STATE_ASSASSIONATION = "ASSASSIONATION"
const STATE_RED_VICTORY = "RED_VICTORY"
const STATE_BLUE_VICTORY = "BLUE_VICTORY"

const STATUS_NOT_STARTED = "NOT_STARTED"
const STATUS_HAS_RESPONSE = "HAS_RESPONSE"
const STATUS_APPROVED = "APPROVED"
const STATUS_COMPLETED = "COMPLETED"

const EVENT_SPEECH = "SPEECH"
