package constants

const STATE_DISCUSSION = "DISCUSSION"
const STATE_VOTING = "VOTING"
const STATE_MISSION = "MISSION"
const STATE_ASSASSINATION_DISCUSSION = "ASSASSINATION_DISCUSSION"
const STATE_ASSASSIONATION_DISCUSSION = "ASSASSIONATION_DISCUSSION"
const STATE_ASSASSINATION = "ASSASSINATION"
const STATE_ASSASSIONATION = "ASSASSIONATION"
const STATE_RED_VICTORY = "RED_VICTORY"
const STATE_BLUE_VICTORY = "BLUE_VICTORY"
